<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role',
        'roles',
        'gender',
        'birth_date',
        'phone',
        'country',
        'address',
        'latitude',
        'longitude',
        'avatar',
        'company_name',
        'company_logo',
        'referral_code',
        'referred_by_id',
        'total_earnings',
        'pending_earnings',
        'withdrawn_earnings',
        'freemopay_wallet_balance',
        'paypal_wallet_balance',
        'otp_code',
        'otp_expires_at',
        'is_profile_complete',
        'preferences',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'otp_code',
        'otp_expires_at',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'birth_date' => 'date',
            'password' => 'hashed',
            'preferences' => 'array',
            'roles' => 'array',
            'is_profile_complete' => 'boolean',
            'otp_expires_at' => 'datetime',
        ];
    }

    /**
     * Get the full name attribute
     */
    public function getNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }

    /**
     * Get all shops for this user
     */
    public function shops(): HasMany
    {
        return $this->hasMany(Shop::class);
    }

    /**
     * Get all products for this user
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    /**
     * Get all orders for this user
     */
    public function orders(): HasMany
    {
        return $this->hasMany(Order::class);
    }

    /**
     * Get favorite products for this user
     */
    public function favorites()
    {
        return $this->belongsToMany(Product::class, 'favorites')->withTimestamps();
    }

    /**
     * Get all contact clicks where this user is the seller
     */
    public function contactClicksAsSeller(): HasMany
    {
        return $this->hasMany(ContactClick::class, 'seller_id');
    }

    /**
     * Get all contact clicks made by this user
     */
    public function contactClicks(): HasMany
    {
        return $this->hasMany(ContactClick::class);
    }

    /**
     * Get conversations where this user is user1
     */
    public function conversationsAsUser1(): HasMany
    {
        return $this->hasMany(Conversation::class, 'user1_id');
    }

    /**
     * Get conversations where this user is user2
     */
    public function conversationsAsUser2(): HasMany
    {
        return $this->hasMany(Conversation::class, 'user2_id');
    }

    /**
     * Get all messages sent by this user
     */
    public function messages(): HasMany
    {
        return $this->hasMany(Message::class, 'sender_id');
    }

    /**
     * Get all device tokens for this user
     */
    public function deviceTokens(): HasMany
    {
        return $this->hasMany(DeviceToken::class);
    }

    /**
     * Get all notifications for this user
     */
    public function notifications(): HasMany
    {
        return $this->hasMany(Notification::class)->latest();
    }

    /**
     * Get the user who referred this user
     */
    public function referrer()
    {
        return $this->belongsTo(User::class, 'referred_by_id');
    }

    /**
     * Get all users referred by this user (niveau 1)
     */
    public function referrals(): HasMany
    {
        return $this->hasMany(User::class, 'referred_by_id');
    }

    /**
     * Get all commissions earned by this user
     */
    public function commissionsEarned(): HasMany
    {
        return $this->hasMany(AffiliateCommission::class, 'affiliate_id');
    }

    /**
     * Get all commissions generated by this user's activity
     */
    public function commissionsGenerated(): HasMany
    {
        return $this->hasMany(AffiliateCommission::class, 'referred_user_id');
    }

    /**
     * Get all vendor packages for this user
     */
    public function vendorPackages(): HasMany
    {
        return $this->hasMany(VendorPackage::class);
    }

    /**
     * Get the active vendor package for this user
     */
    public function activeVendorPackage(): HasOne
    {
        return $this->hasOne(VendorPackage::class)
            ->where('status', 'active')
            ->where('expires_at', '>', now())
            ->latest('purchased_at');
    }

    /**
     * Get all wallet transactions for this user
     */
    public function walletTransactions(): HasMany
    {
        return $this->hasMany(WalletTransaction::class);
    }

    /**
     * Get all withdrawals for this user
     */
    public function withdrawals(): HasMany
    {
        return $this->hasMany(PlatformWithdrawal::class);
    }

    /**
     * Get the deliverer company for this user
     */
    public function delivererCompany(): HasOne
    {
        return $this->hasOne(DelivererCompany::class);
    }

    /**
     * Get all sync codes for this deliverer
     */
    public function delivererSyncCodes(): HasMany
    {
        return $this->hasMany(DelivererSyncCode::class);
    }

    /**
     * Get the latest valid sync code
     */
    public function latestValidSyncCode(): HasOne
    {
        return $this->hasOne(DelivererSyncCode::class)
            ->where('is_used', false)
            ->where(function ($query) {
                $query->whereNull('expires_at')
                      ->orWhere('expires_at', '>', now());
            })
            ->latest();
    }

    /**
     * Get total wallet balance (FreeMoPay + PayPal)
     */
    public function getTotalWalletBalanceAttribute(): float
    {
        return ($this->freemopay_wallet_balance ?? 0) + ($this->paypal_wallet_balance ?? 0);
    }

    /**
     * Get formatted total wallet balance
     */
    public function getFormattedWalletBalanceAttribute(): string
    {
        return number_format($this->total_wallet_balance, 0, ',', ' ') . ' FCFA';
    }

    /**
     * Get formatted FreeMoPay wallet balance
     */
    public function getFormattedFreemopayBalanceAttribute(): string
    {
        return number_format($this->freemopay_wallet_balance ?? 0, 0, ',', ' ') . ' FCFA';
    }

    /**
     * Get formatted PayPal wallet balance
     */
    public function getFormattedPaypalBalanceAttribute(): string
    {
        return number_format($this->paypal_wallet_balance ?? 0, 0, ',', ' ') . ' FCFA';
    }

    /**
     * Boot method to generate referral code
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($user) {
            if (empty($user->referral_code)) {
                $user->referral_code = strtoupper(substr($user->first_name, 0, 3) . substr($user->last_name, 0, 3) . rand(1000, 9999));
            }
        });
    }

    /**
     * Get total number of direct referrals
     */
    public function getTotalReferralsAttribute(): int
    {
        return $this->referrals()->count();
    }

    /**
     * Get all referrals recursively (niveau 1, 2, 3)
     */
    public function getAllReferralsTree()
    {
        $settings = AffiliateSetting::getSettings();
        $maxLevels = $settings->max_levels;

        return $this->getReferralsRecursive(1, $maxLevels);
    }

    private function getReferralsRecursive($currentLevel, $maxLevel)
    {
        if ($currentLevel > $maxLevel) {
            return collect();
        }

        $referrals = $this->referrals()->with('referrals')->get();

        $result = $referrals->map(function ($referral) use ($currentLevel, $maxLevel) {
            return [
                'user' => $referral,
                'level' => $currentLevel,
                'children' => $referral->getReferralsRecursive($currentLevel + 1, $maxLevel),
            ];
        });

        return $result;
    }

    // ================================
    // ROLES MANAGEMENT
    // ================================

    /**
     * Check if user has a specific role
     */
    public function hasRole(string $role): bool
    {
        if (is_array($this->roles)) {
            return in_array($role, $this->roles);
        }
        // Fallback to old role column
        return $this->role === $role;
    }

    /**
     * Check if user has any of the given roles
     */
    public function hasAnyRole(array $roles): bool
    {
        foreach ($roles as $role) {
            if ($this->hasRole($role)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Add a role to the user
     */
    public function addRole(string $role): void
    {
        $roles = is_array($this->roles) ? $this->roles : [$this->role];

        if (!in_array($role, $roles)) {
            $roles[] = $role;
            $this->roles = $roles;
            // Keep role column updated with primary role
            $this->role = $roles[0];
            $this->save();
        }
    }

    /**
     * Remove a role from the user
     */
    public function removeRole(string $role): void
    {
        $roles = is_array($this->roles) ? $this->roles : [$this->role];

        $roles = array_filter($roles, fn($r) => $r !== $role);

        if (empty($roles)) {
            $roles = ['client']; // Default role
        }

        $this->roles = array_values($roles);
        $this->role = $roles[0];
        $this->save();
    }

    /**
     * Get all user roles
     */
    public function getRoles(): array
    {
        return is_array($this->roles) ? $this->roles : [$this->role];
    }
}

