<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role',
        'gender',
        'birth_date',
        'phone',
        'country',
        'address',
        'latitude',
        'longitude',
        'avatar',
        'company_name',
        'company_logo',
        'referral_code',
        'referred_by_id',
        'total_earnings',
        'pending_earnings',
        'withdrawn_earnings',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'birth_date' => 'date',
            'password' => 'hashed',
        ];
    }

    /**
     * Get the full name attribute
     */
    public function getNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }

    /**
     * Get all shops for this user
     */
    public function shops(): HasMany
    {
        return $this->hasMany(Shop::class);
    }

    /**
     * Get all products for this user
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    /**
     * Get all contact clicks where this user is the seller
     */
    public function contactClicksAsSeller(): HasMany
    {
        return $this->hasMany(ContactClick::class, 'seller_id');
    }

    /**
     * Get all contact clicks made by this user
     */
    public function contactClicks(): HasMany
    {
        return $this->hasMany(ContactClick::class);
    }

    /**
     * Get conversations where this user is user1
     */
    public function conversationsAsUser1(): HasMany
    {
        return $this->hasMany(Conversation::class, 'user1_id');
    }

    /**
     * Get conversations where this user is user2
     */
    public function conversationsAsUser2(): HasMany
    {
        return $this->hasMany(Conversation::class, 'user2_id');
    }

    /**
     * Get all messages sent by this user
     */
    public function messages(): HasMany
    {
        return $this->hasMany(Message::class, 'sender_id');
    }

    /**
     * Get the user who referred this user
     */
    public function referrer()
    {
        return $this->belongsTo(User::class, 'referred_by_id');
    }

    /**
     * Get all users referred by this user (niveau 1)
     */
    public function referrals(): HasMany
    {
        return $this->hasMany(User::class, 'referred_by_id');
    }

    /**
     * Get all commissions earned by this user
     */
    public function commissionsEarned(): HasMany
    {
        return $this->hasMany(AffiliateCommission::class, 'affiliate_id');
    }

    /**
     * Get all commissions generated by this user's activity
     */
    public function commissionsGenerated(): HasMany
    {
        return $this->hasMany(AffiliateCommission::class, 'referred_user_id');
    }

    /**
     * Boot method to generate referral code
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($user) {
            if (empty($user->referral_code)) {
                $user->referral_code = strtoupper(substr($user->first_name, 0, 3) . substr($user->last_name, 0, 3) . rand(1000, 9999));
            }
        });
    }

    /**
     * Get total number of direct referrals
     */
    public function getTotalReferralsAttribute(): int
    {
        return $this->referrals()->count();
    }

    /**
     * Get all referrals recursively (niveau 1, 2, 3)
     */
    public function getAllReferralsTree()
    {
        $settings = AffiliateSetting::getSettings();
        $maxLevels = $settings->max_levels;

        return $this->getReferralsRecursive(1, $maxLevels);
    }

    private function getReferralsRecursive($currentLevel, $maxLevel)
    {
        if ($currentLevel > $maxLevel) {
            return collect();
        }

        $referrals = $this->referrals()->with('referrals')->get();

        $result = $referrals->map(function ($referral) use ($currentLevel, $maxLevel) {
            return [
                'user' => $referral,
                'level' => $currentLevel,
                'children' => $referral->getReferralsRecursive($currentLevel + 1, $maxLevel),
            ];
        });

        return $result;
    }
}

